version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
#    ports:
#      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - my-backend

  backend:
    build:
      context: ./backend
    container_name: nestjs_backend
    depends_on:
      - db
#    ports:
#      - "3001:3000"
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASS: password
      DB_NAME: mydatabase
    networks:
      - my-backend

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - my-frontend
      - my-backend

networks:
  my-frontend:
    driver: bridge
  my-backend:
    driver: bridge


volumes:
  db-data:
